import Head from "next/head";

import { Inconsolata, Inter, Lora } from "@next/font/google";

import styles from "@/styles/Home.module.scss";

import { Header, Main } from "@/components";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });
const inconsolata = Inconsolata({ subsets: ["latin"] });

export default function Home() {
    const [fontFamily, setFontFamily] = useState(inter);

    const handleFontFamily = (font: string) => {
        console.log(font);

        if (font === "inter") {
            setFontFamily(inter);
        }
        if (font === "lora") {
            setFontFamily(lora);
        }
        if (font === "inconsolata") {
            setFontFamily(inconsolata);
        }
    };

    return (
        <div className={`${styles.home_container} ${fontFamily.className}`}>
            <Head>
                <title>Frontend Mentor | Dictionary web app</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/assets/images/favicon-32x32.png" />
            </Head>
            <div className={styles.container}>
                <Header chooseFontFamily={handleFontFamily} />
                <Main />
            </div>
        </div>
    );
}
